export default [
    {
       id: 1,
       name: "Mr and Mrs Johnson",
       email: "you@me.com",
       eventTitle: "Wedding",
       date: "Sept 10, 2019",
       location: "Big club",
       address: "2114 West 10th",
       city: "James Town",
       state: "MI",
       time: "5pm",
       budget: "$1000",
       description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus minus corrupti earum mollitia numquam veritatis vel explicabo consequatur quasi voluptas.",

    },
    {
        id: 2,
        name: "Mr and Mr Smith",
        email: "hey@me.com",
        eventTitle: "Birthday",
        date: "Sept 23, 2019",
        location: "Yacht Club",
        address: "3654 West Palm Beach",
        city: "Boca Rotan",
        state: "FL",
        time: "12pm",
        budget: "$8000",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus minus corrupti earum mollitia numquam veritatis vel explicabo consequatur quasi voluptas.",

     },
     {
        id: 3,
        name: "Karen Johnson",
        email: "k@me.com",
        eventTitle: "Festival",
        date: "Oct 10, 2019",
        location: "Howard Club",
        address: "Nw 3rd Ave",
        city: "Seattle",
        state: "WA",
        time: "9pm",
        budget: "$1500",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus minus corrupti earum mollitia numquam veritatis vel explicabo consequatur quasi voluptas.",

     },
     {
      id: 4,
      name: "Frank Zimmerman",
      email: "frankz@me.com",
      eventTitle: "Company Party",
      date: "Dec 15, 2019",
      location: "McDonald's",
      address: "5150 Evergreen St",
      city: "Boise",
      state: "ID",
      time: "11am",
      budget: "$500",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus minus corrupti earum mollitia numquam veritatis vel explicabo consequatur quasi voluptas.",

   },

   {
      id: 5,
      name: "Sally Gerky",
      email: "sallyg@me.com",
      eventTitle: "PTO Meeting",
      date: "Nov 15, 2019",
      location: "Barney's Bar and Grill",
      address: "West and 7th Ave",
      city: "Chicago",
      state: "IL",
      time: "9pm",
      budget: "$2500",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus minus corrupti earum mollitia numquam veritatis vel explicabo consequatur quasi voluptas.",

   },

];
